package com.supplytrack;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;

@Table("events") // Maps this entity to a database table named 'events'
public class Event {

    @Id // Primary key for the event
    private Long id;
    private Long productId; // Foreign key to the Product this event relates to
    private String eventType; // Type of event (e.g., "HARVESTED", "SHIPPED", "RECEIVED", "QUALITY_CHECK")
    private String eventDescription; // Detailed description of the event
    private LocalDateTime timestamp; // When the event occurred
    private String location; // Where the event occurred
    private Long actorUserId; // ID of the user who performed this event

    // Constructor for Spring Data JDBC to use when loading from database
    public Event(Long id, Long productId, String eventType, String eventDescription, LocalDateTime timestamp, String location, Long actorUserId) {
        this.id = id;
        this.productId = productId;
        this.eventType = eventType;
        this.eventDescription = eventDescription;
        this.timestamp = timestamp;
        this.location = location;
        this.actorUserId = actorUserId;
    }

    // Static factory method for creating NEW Event objects (ID will be generated by DB)
    public static Event createNewEvent(Long productId, String eventType, String eventDescription, String location, Long actorUserId) {
        return new Event(null, productId, eventType, eventDescription, LocalDateTime.now(), location, actorUserId);
    }

    // --- Getters and Setters ---
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getEventType() {
        return eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public String getEventDescription() {
        return eventDescription;
    }

    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public Long getActorUserId() {
        return actorUserId;
    }

    public void setActorUserId(Long actorUserId) {
        this.actorUserId = actorUserId;
    }
}
