package com.supplytrack;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime; // For timestamps

@Table("products") // Maps this entity to a database table named 'products'
public class Product {

    @Id // Marks this field as the primary key
    private Long id;
    private String name; // Name of the product (e.g., "Organic Tomatoes")
    private String origin; // Where it originated (e.g., "Farm XYZ, California")
    private String currentStatus; // Current status (e.g., "HARVESTED", "IN_TRANSIT", "AT_RESTAURANT")
    private String currentLocation; // Current physical location (e.g., "Warehouse A", "Restaurant Kitchen")
    private LocalDateTime createdDate; // Timestamp when product was initially created/harvested
    private Long ownerUserId; // ID of the current owner/responsible party (e.g., farmer, distributor, restaurant)

    // Constructor for Spring Data JDBC to use when loading from database
    public Product(Long id, String name, String origin, String currentStatus, String currentLocation, LocalDateTime createdDate, Long ownerUserId) {
        this.id = id;
        this.name = name;
        this.origin = origin;
        this.currentStatus = currentStatus;
        this.currentLocation = currentLocation;
        this.createdDate = createdDate;
        this.ownerUserId = ownerUserId;
    }

    // Static factory method for creating NEW Product objects (ID will be generated by DB)
    public static Product createNewProduct(String name, String origin, String currentStatus, String currentLocation, Long ownerUserId) {
        return new Product(null, name, origin, currentStatus, currentLocation, LocalDateTime.now(), ownerUserId);
    }

    // --- Getters and Setters ---
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getOrigin() {
        return origin;
    }

    public void setOrigin(String origin) {
        this.origin = origin;
    }

    public String getCurrentStatus() {
        return currentStatus;
    }

    public void setCurrentStatus(String currentStatus) {
        this.currentStatus = currentStatus;
    }

    public String getCurrentLocation() {
        return currentLocation;
    }

    public void setCurrentLocation(String currentLocation) {
        this.currentLocation = currentLocation;
    }

    public LocalDateTime getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    public Long getOwnerUserId() {
        return ownerUserId;
    }

    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }
}